['1a0s', 'FOBS::f_obs is None::i_obs is None']
['1am7', 'FOBS::f_obs is None::i_obs is None']
['1av2', 'I(+),SIGI(+),I(-),SIGI(-)::f_obs is None::i_obs is None']
['1axg', 'FOBS::f_obs is None::i_obs is None']
['1b26', 'FOBS::f_obs is None::i_obs is None']
['1b7b', 'FOBS::f_obs is None::i_obs is None']
['1b8d', 'FOBS::f_obs is None::i_obs is None']
['1bxz', 'f_obs is None::']
['1c5e', 'f_obs is None::']
['1dao', 'f_obs is None::']
['1dwn', 'FOBS::f_obs is None::i_obs is None']
['1dzl', 'f_obs is None::']
['1e3d', 'f_obs is None::']
['1ei7', 'f_obs is None::']
['1fui', 'FOBS::f_obs is None::i_obs is None']
['1gy8', 'F(+),SIGF(+),F(-),SIGF(-)::f_obs is None::i_obs is None']
['1gzh', 'F(+),SIGF(+),F(-),SIGF(-)::f_obs is None::i_obs is None']
['1hcy', 'Warning: merging non-unique data::FOBS::f_obs is None::i_obs is None']
['1hh3', 'f_obs is None::']
['1hha', 'f_obs is None::']
['1hhc', 'f_obs is None::']
['1hhf', 'f_obs is None::']
['1hhu', 'f_obs is None::']
['1hhz', 'f_obs is None::']
['1hkd', 'f_obs is None::']
['1kmn', 'f_obs is None::']
['1llc', 'FOBS::f_obs is None::i_obs is None']
['1mms', 'F(+),SIGF(+),F(-),SIGF(-)::f_obs is None::i_obs is None']
['1mpr', 'FOBS::f_obs is None::i_obs is None']
['1nal', 'FOBS::f_obs is None::i_obs is None']
['1o4z', 'F(+),SIGF(+),F(-),SIGF(-)::I(+),SIGI(+),I(-),SIGI(-)::f_obs is None::i_obs is None']
['1o7j', 'f_obs is None::']
['1ofs', 'I(+),SIGI(+),I(-),SIGI(-)::f_obs is None::i_obs is None']
['1ovo', 'FOBS::f_obs is None::i_obs is None']
['1qox', 'f_obs is None::']
['1swb', 'f_obs is None::']
['1swd', 'f_obs is None::']
['1swe', 'f_obs is None::']
['1swf', 'f_obs is None::']
['1swg', 'f_obs is None::']
['1swh', 'f_obs is None::']
['1swj', 'f_obs is None::']
['1swk', 'f_obs is None::']
['1swl', 'f_obs is None::']
['1swn', 'f_obs is None::']
['1swo', 'f_obs is None::']
['1swp', 'f_obs is None::']
['1swq', 'f_obs is None::']
['1swr', 'f_obs is None::']
['1tnv', 'FOBS::f_obs is None::i_obs is None']
['1ugi', 'f_obs is None::']
['1up4', 'F(+),F(-)::I(+),SIGI(+),I(-),SIGI(-)::f_obs is None::i_obs is None']
['1up6', 'F(+),SIGF(+),F(-),SIGF(-)::I(+),SIGI(+),I(-),SIGI(-)::f_obs is None::i_obs is None']
['1up7', 'F(+),SIGF(+),F(-),SIGF(-)::I(+),SIGI(+),I(-),SIGI(-)::f_obs is None::i_obs is None']
['1upm', 'f_obs is None::']
['1upp', 'f_obs is None::']
['1vcr', 'f_obs is None::']
['1vyw', 'F(+),SIGF(+),F(-),SIGF(-)::I(+),SIGI(+),I(-),SIGI(-)::f_obs is None::i_obs is None']
['1vzm', 'f_obs is None::']
['1w39', 'f_obs.crystal_symmetry is not similar to crystal symmetry::']
['1w3m', 'f_obs is None::']
['1w7q', 'f_obs is None::']
['1w7r', 'f_obs is None::']
['1wc7', 'f_obs is None::']
['1x35', 'f_obs is None::']
['2a5h', 'Warning: merging non-unique data::I1(+),SIGI1(+),I1(-),SIGI1(-)::I2(+),SIGI2(+),I2(-),SIGI2(-)::f_obs is None::i_obs is None']
['2bht', 'Warning: merging non-unique data::I(+),SIGI(+),I(-),SIGI(-)::f_obs is None::i_obs is None']
['2boy', 'f_obs is None::']
['2hmg', 'FOBS::f_obs is None::i_obs is None']
['2izw', 'f_obs is None::']
['2mpr', 'FOBS::f_obs is None::i_obs is None']
['2rsl', 'f_obs is None::']
['2ux2', 'FOBS::f_obs is None::i_obs is None']
['2v4j', 'f_obs.crystal_symmetry is not similar to crystal symmetry::']
['2vkr', 'f_obs is None::']
['2w4y', 'f_obs is None::']
['2xvt', 'Warning: merging non-unique data::DANO::FOBS-1,SIGFOBS-1::DANO-1,SIGDANO-1::F(+),SIGF(+),F(-),SIGF(-)::I(+),SIGI(+),I(-),SIGI(-)::FOBS-2,SIGFOBS-2::IOBS-1,SIGIOBS-1::DANO-2,SIGDANO-2::R-free-flags-2::F-1(+),SIGF-1(+),F-1(-),SIGF-1(-)::I-1(+),SIGI-1(+),I-1(-),SIGI-1(-)::FOBS-3,SIGFOBS-3::IOBS-2,SIGIOBS-2::DANO-3,SIGDANO-3::R-free-flags-3::F-2(+),SIGF-2(+),F-2(-),SIGF-2(-)::I-2(+),SIGI-2(+),I-2(-),SIGI-2(-)::f_obs.crystal_symmetry is not similar to crystal symmetry::']
['2yaw', 'f_obs is None::']
['3cf2', 'F(+),SIGF(+),F(-),SIGF(-)::f_obs is None::i_obs is None']
['3dar', 'Warning: merging non-unique data::HLA,HLB,HLC,HLD::DANO,SIGDANO::F(+),SIGF(+),F(-),SIGF(-)::I(+),SIGI(+),I(-),SIGI(-)::f_obs.crystal_symmetry is not similar to crystal symmetry::']
['3n97', 'f_obs.crystal_symmetry is not similar to crystal symmetry::']
['3q7h', 'f_obs is None::']
['3sod', 'Warning: merging non-unique data::FOBS::f_obs is None::i_obs is None']
['3u1n', 'F(+),SIGF(+),F(-),SIGF(-)::I(+),SIGI(+),I(-),SIGI(-)::f_obs is None::i_obs is None']
['4a63', 'Warning: merging non-unique data::DANO,SIGDANO::F(+),SIGF(+),F(-),SIGF(-)::I(+),SIGI(+),I(-),SIGI(-)::f_obs.crystal_symmetry is not similar to crystal symmetry::']
['4afl', 'f_obs.crystal_symmetry is not similar to crystal symmetry::']
['4b3z', 'f_obs is None::']
['4bik', 'f_obs is None::']
['4ejf', 'f_obs is None::']
['4ev0', 'f_obs is None::']
['4hkj', 'Warning: merging non-unique data::IOBS-11,SIGIOBS-11::I2(+),SIGI2(+),I2(-),SIGI2(-)::f_obs is None::']
['4hmg', 'FOBS::f_obs is None::i_obs is None']
['4j26', 'f_obs.crystal_symmetry is not similar to crystal symmetry::']
['5cro', 'FOBS::f_obs is None::i_obs is None']
['5hmg', 'FOBS::f_obs is None::i_obs is None']